# Generated by Django 3.2 on 2022-09-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_likes'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liked',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
