# Generated by Django 3.2 on 2022-09-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='liked',
        ),
    ]
